"use client";

import { useState } from "react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { z } from "zod";
import { toast } from "sonner";
import { sendMail } from "@/lib/send-mail";
import { Loader2, CheckCircle2, AlertTriangle } from "lucide-react";

const REASONS = [
  "I no longer use the app",
  "Privacy or data concerns",
  "Switching to a different app",
  "The app isn't working for me",
  "I found a bug that lost my data",
  "Other",
] as const;

const schema = z.object({
  name: z.string().min(2, "Please enter your name"),
  email: z.string().email("Please enter a valid email address"),
  reason: z.enum(REASONS, { required_error: "Please select a reason" }),
  details: z.string().max(1000, "Max 1000 characters").optional(),
  confirm: z.literal(true, {
    errorMap: () => ({ message: "You must confirm to proceed" }),
  }),
});

type FormValues = z.infer<typeof schema>;

function buildHtml(values: FormValues) {
  const now = new Date().toLocaleString("en-IN", {
    timeZone: "Asia/Kolkata",
    dateStyle: "long",
    timeStyle: "short",
  });

  return `
<!DOCTYPE html>
<html>
<head><meta charset="utf-8"/></head>
<body style="margin:0;padding:0;background:#f8fafc;font-family:system-ui,sans-serif;">
  <table width="100%" cellpadding="0" cellspacing="0" style="background:#f8fafc;padding:32px 16px;">
    <tr><td align="center">
      <table width="600" cellpadding="0" cellspacing="0" style="background:#ffffff;border-radius:16px;overflow:hidden;border:1px solid #e2e8f0;">
        <!-- Header -->
        <tr>
          <td style="background:#0081B3;padding:28px 32px;">
            <p style="margin:0;font-size:11px;font-weight:700;letter-spacing:2px;color:rgba(255,255,255,0.65);text-transform:uppercase;">BusinessX</p>
            <h1 style="margin:6px 0 0;font-size:22px;font-weight:800;color:#ffffff;">Data Deletion Request</h1>
          </td>
        </tr>
        <!-- Body -->
        <tr>
          <td style="padding:32px;">
            <p style="margin:0 0 24px;font-size:14px;color:#64748b;line-height:1.6;">
              A user has submitted a request to delete their BusinessX account data. Please process this within <strong>30 days</strong>.
            </p>

            <!-- Fields -->
            <table width="100%" cellpadding="0" cellspacing="0">
              ${[
                ["Full Name", values.name],
                ["Email Address", values.email],
                ["Reason", values.reason],
              ]
                .map(
                  ([label, value]) => `
              <tr>
                <td style="padding:10px 0;border-bottom:1px solid #f1f5f9;">
                  <p style="margin:0;font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:1px;color:#94a3b8;">${label}</p>
                  <p style="margin:4px 0 0;font-size:15px;font-weight:600;color:#1e293b;">${value}</p>
                </td>
              </tr>`
                )
                .join("")}
              ${
                values.details
                  ? `<tr>
                <td style="padding:10px 0;border-bottom:1px solid #f1f5f9;">
                  <p style="margin:0;font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:1px;color:#94a3b8;">Additional Details</p>
                  <p style="margin:4px 0 0;font-size:15px;color:#1e293b;white-space:pre-wrap;">${values.details}</p>
                </td>
              </tr>`
                  : ""
              }
              <tr>
                <td style="padding:10px 0;">
                  <p style="margin:0;font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:1px;color:#94a3b8;">Submitted At</p>
                  <p style="margin:4px 0 0;font-size:15px;font-weight:600;color:#1e293b;">${now} IST</p>
                </td>
              </tr>
            </table>

            <!-- CTA note -->
            <div style="margin-top:28px;background:#fef9c3;border:1px solid #fde68a;border-radius:10px;padding:14px 16px;">
              <p style="margin:0;font-size:13px;color:#92400e;line-height:1.5;">
                <strong>Action required:</strong> Delete all data associated with the email address above from the BusinessX database and any backups. Reply to the user at the address above once complete.
              </p>
            </div>
          </td>
        </tr>
        <!-- Footer -->
        <tr>
          <td style="background:#f8fafc;padding:16px 32px;border-top:1px solid #e2e8f0;">
            <p style="margin:0;font-size:12px;color:#94a3b8;text-align:center;">
              This email was automatically generated by the BusinessX website · businessxteam@gmail.com
            </p>
          </td>
        </tr>
      </table>
    </td></tr>
  </table>
</body>
</html>`;
}

function buildText(values: FormValues) {
  const now = new Date().toLocaleString("en-IN", { timeZone: "Asia/Kolkata" });
  return [
    "DATA DELETION REQUEST — BusinessX",
    "=".repeat(40),
    `Name:    ${values.name}`,
    `Email:   ${values.email}`,
    `Reason:  ${values.reason}`,
    values.details ? `Details: ${values.details}` : "",
    `Submitted: ${now} IST`,
    "=".repeat(40),
    "Please process this deletion request within 30 days.",
  ]
    .filter(Boolean)
    .join("\n");
}

export default function DeleteRequestForm() {
  const [submitted, setSubmitted] = useState(false);

  const {
    register,
    handleSubmit,
    formState: { errors, isSubmitting },
  } = useForm<FormValues>({
    resolver: zodResolver(schema),
  });

  const onSubmit = async (values: FormValues) => {
    const result = await sendMail({
      email: values.email,
      subject: `Data Deletion Request — ${values.name} (${values.email})`,
      text: buildText(values),
      html: buildHtml(values),
    });

    if (result?.messageId) {
      setSubmitted(true);
    } else {
      toast.error("Failed to send request. Please email us directly at businessxteam@gmail.com");
    }
  };

  if (submitted) {
    return (
      <div className="flex flex-col items-center text-center py-10 px-6">
        <div className="w-16 h-16 rounded-full bg-green-100 flex items-center justify-center mb-5">
          <CheckCircle2 className="w-8 h-8 text-green-600" />
        </div>
        <h2 className="text-xl font-black text-[#04111D] mb-2">Request Received</h2>
        <p className="text-slate-500 text-sm max-w-xs leading-relaxed">
          We&apos;ve received your data deletion request and will process it within{" "}
          <strong>30 days</strong>. You&apos;ll receive a confirmation at your email
          address once complete.
        </p>
      </div>
    );
  }

  return (
    <form onSubmit={handleSubmit(onSubmit)} className="space-y-5">
      {/* Name */}
      <div>
        <label className="block text-sm font-semibold text-slate-700 mb-1.5">
          Full Name <span className="text-red-500">*</span>
        </label>
        <input
          {...register("name")}
          placeholder="Rajesh Kumar"
          className="w-full h-11 rounded-xl border border-slate-200 bg-white px-3.5 text-sm text-slate-800 placeholder:text-slate-400 focus:outline-none focus:ring-2 focus:ring-[#0081B3]/40 focus:border-[#0081B3] transition"
        />
        {errors.name && (
          <p className="mt-1.5 text-xs text-red-500">{errors.name.message}</p>
        )}
      </div>

      {/* Email */}
      <div>
        <label className="block text-sm font-semibold text-slate-700 mb-1.5">
          Registered Email Address <span className="text-red-500">*</span>
        </label>
        <input
          {...register("email")}
          type="email"
          placeholder="you@example.com"
          className="w-full h-11 rounded-xl border border-slate-200 bg-white px-3.5 text-sm text-slate-800 placeholder:text-slate-400 focus:outline-none focus:ring-2 focus:ring-[#0081B3]/40 focus:border-[#0081B3] transition"
        />
        {errors.email && (
          <p className="mt-1.5 text-xs text-red-500">{errors.email.message}</p>
        )}
      </div>

      {/* Reason */}
      <div>
        <label className="block text-sm font-semibold text-slate-700 mb-1.5">
          Reason for Deletion <span className="text-red-500">*</span>
        </label>
        <select
          {...register("reason")}
          className="w-full h-11 rounded-xl border border-slate-200 bg-white px-3.5 text-sm text-slate-800 focus:outline-none focus:ring-2 focus:ring-[#0081B3]/40 focus:border-[#0081B3] transition appearance-none"
          defaultValue=""
        >
          <option value="" disabled>
            Select a reason…
          </option>
          {REASONS.map((r) => (
            <option key={r} value={r}>
              {r}
            </option>
          ))}
        </select>
        {errors.reason && (
          <p className="mt-1.5 text-xs text-red-500">{errors.reason.message}</p>
        )}
      </div>

      {/* Details */}
      <div>
        <label className="block text-sm font-semibold text-slate-700 mb-1.5">
          Additional Details{" "}
          <span className="text-slate-400 font-normal">(optional)</span>
        </label>
        <textarea
          {...register("details")}
          rows={3}
          placeholder="Anything else you'd like us to know…"
          className="w-full rounded-xl border border-slate-200 bg-white px-3.5 py-2.5 text-sm text-slate-800 placeholder:text-slate-400 focus:outline-none focus:ring-2 focus:ring-[#0081B3]/40 focus:border-[#0081B3] transition resize-none"
        />
        {errors.details && (
          <p className="mt-1.5 text-xs text-red-500">{errors.details.message}</p>
        )}
      </div>

      {/* Warning banner */}
      <div className="flex items-start gap-3 bg-amber-50 border border-amber-200 rounded-xl p-4">
        <AlertTriangle className="w-4 h-4 text-amber-600 mt-0.5 flex-shrink-0" />
        <p className="text-xs text-amber-800 leading-relaxed">
          This action is <strong>permanent and irreversible</strong>. All your inventory,
          sales history, and reports will be deleted. Export your data first if you
          need a copy.
        </p>
      </div>

      {/* Confirm checkbox */}
      <div>
        <label className="flex items-start gap-3 cursor-pointer group">
          <input
            type="checkbox"
            {...register("confirm")}
            className="mt-0.5 w-4 h-4 rounded border-slate-300 text-[#0081B3] focus:ring-[#0081B3]/40 flex-shrink-0 cursor-pointer"
          />
          <span className="text-sm text-slate-600 leading-relaxed group-hover:text-slate-800 transition">
            I understand that deleting my data is permanent and cannot be undone.
          </span>
        </label>
        {errors.confirm && (
          <p className="mt-1.5 text-xs text-red-500">{errors.confirm.message}</p>
        )}
      </div>

      {/* Submit */}
      <button
        type="submit"
        disabled={isSubmitting}
        className="w-full h-11 rounded-xl bg-[#0081B3] hover:bg-[#0070A0] disabled:opacity-60 text-white font-bold text-sm transition-colors flex items-center justify-center gap-2"
      >
        {isSubmitting ? (
          <>
            <Loader2 className="w-4 h-4 animate-spin" />
            Sending Request…
          </>
        ) : (
          "Submit Deletion Request"
        )}
      </button>

      <p className="text-center text-xs text-slate-400">
        Processing takes up to 30 days · Questions?{" "}
        <a
          href="mailto:businessxteam@gmail.com"
          className="text-[#0081B3] hover:underline"
        >
          businessxteam@gmail.com
        </a>
      </p>
    </form>
  );
}
