"use client";

import { useState } from "react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { z } from "zod";
import { toast } from "sonner";
import { sendMail } from "@/lib/send-mail";
import { Loader2, CheckCircle2 } from "lucide-react";

const TOPICS = [
  "Bug Report",
  "Account or Billing",
  "Feature Request",
  "General Question",
  "Other",
] as const;

const schema = z.object({
  name: z.string().min(2, "Please enter your name"),
  email: z.string().email("Please enter a valid email address"),
  topic: z.enum(TOPICS, { required_error: "Please select a topic" }),
  message: z
    .string()
    .min(10, "Please give us a few more details")
    .max(2000, "Max 2000 characters"),
});

type FormValues = z.infer<typeof schema>;

function buildHtml(values: FormValues) {
  const now = new Date().toLocaleString("en-IN", {
    timeZone: "Asia/Kolkata",
    dateStyle: "long",
    timeStyle: "short",
  });

  return `
<!DOCTYPE html>
<html>
<head><meta charset="utf-8"/></head>
<body style="margin:0;padding:0;background:#f8fafc;font-family:system-ui,sans-serif;">
  <table width="100%" cellpadding="0" cellspacing="0" style="background:#f8fafc;padding:32px 16px;">
    <tr><td align="center">
      <table width="600" cellpadding="0" cellspacing="0" style="background:#ffffff;border-radius:16px;overflow:hidden;border:1px solid #e2e8f0;">
        <!-- Header -->
        <tr>
          <td style="background:#0081B3;padding:28px 32px;">
            <p style="margin:0;font-size:11px;font-weight:700;letter-spacing:2px;color:rgba(255,255,255,0.65);text-transform:uppercase;">BusinessX</p>
            <h1 style="margin:6px 0 0;font-size:22px;font-weight:800;color:#ffffff;">Support Request</h1>
          </td>
        </tr>
        <!-- Body -->
        <tr>
          <td style="padding:32px;">
            <p style="margin:0 0 24px;font-size:14px;color:#64748b;line-height:1.6;">
              A visitor submitted a support request through the website.
            </p>

            <!-- Fields -->
            <table width="100%" cellpadding="0" cellspacing="0">
              ${[
                ["Full Name", values.name],
                ["Email Address", values.email],
                ["Topic", values.topic],
              ]
                .map(
                  ([label, value]) => `
              <tr>
                <td style="padding:10px 0;border-bottom:1px solid #f1f5f9;">
                  <p style="margin:0;font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:1px;color:#94a3b8;">${label}</p>
                  <p style="margin:4px 0 0;font-size:15px;font-weight:600;color:#1e293b;">${value}</p>
                </td>
              </tr>`
                )
                .join("")}
              <tr>
                <td style="padding:10px 0;border-bottom:1px solid #f1f5f9;">
                  <p style="margin:0;font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:1px;color:#94a3b8;">Message</p>
                  <p style="margin:4px 0 0;font-size:15px;color:#1e293b;white-space:pre-wrap;">${values.message}</p>
                </td>
              </tr>
              <tr>
                <td style="padding:10px 0;">
                  <p style="margin:0;font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:1px;color:#94a3b8;">Submitted At</p>
                  <p style="margin:4px 0 0;font-size:15px;font-weight:600;color:#1e293b;">${now} IST</p>
                </td>
              </tr>
            </table>
          </td>
        </tr>
        <!-- Footer -->
        <tr>
          <td style="background:#f8fafc;padding:16px 32px;border-top:1px solid #e2e8f0;">
            <p style="margin:0;font-size:12px;color:#94a3b8;text-align:center;">
              This email was automatically generated by the BusinessX website · businessxteam@gmail.com
            </p>
          </td>
        </tr>
      </table>
    </td></tr>
  </table>
</body>
</html>`;
}

function buildText(values: FormValues) {
  const now = new Date().toLocaleString("en-IN", { timeZone: "Asia/Kolkata" });
  return [
    "SUPPORT REQUEST — BusinessX",
    "=".repeat(40),
    `Name:    ${values.name}`,
    `Email:   ${values.email}`,
    `Topic:   ${values.topic}`,
    `Message: ${values.message}`,
    `Submitted: ${now} IST`,
    "=".repeat(40),
  ].join("\n");
}

export default function SupportRequestForm() {
  const [submitted, setSubmitted] = useState(false);

  const {
    register,
    handleSubmit,
    formState: { errors, isSubmitting },
  } = useForm<FormValues>({
    resolver: zodResolver(schema),
  });

  const onSubmit = async (values: FormValues) => {
    const result = await sendMail({
      email: values.email,
      subject: `Support Request — ${values.topic} (${values.name})`,
      text: buildText(values),
      html: buildHtml(values),
    });

    if (result?.messageId) {
      setSubmitted(true);
    } else {
      toast.error("Failed to send message. Please email us directly at businessxteam@gmail.com");
    }
  };

  if (submitted) {
    return (
      <div className="flex flex-col items-center text-center py-10 px-6">
        <div className="w-16 h-16 rounded-full bg-green-100 flex items-center justify-center mb-5">
          <CheckCircle2 className="w-8 h-8 text-green-600" />
        </div>
        <h2 className="text-xl font-black text-[#04111D] mb-2">Message Sent</h2>
        <p className="text-slate-500 text-sm max-w-xs leading-relaxed">
          Thanks for reaching out. Our team typically replies within{" "}
          <strong>1–2 business days</strong> at the email address you provided.
        </p>
      </div>
    );
  }

  return (
    <form onSubmit={handleSubmit(onSubmit)} className="space-y-5">
      {/* Name */}
      <div>
        <label className="block text-sm font-semibold text-slate-700 mb-1.5">
          Full Name <span className="text-red-500">*</span>
        </label>
        <input
          {...register("name")}
          placeholder="Rajesh Kumar"
          className="w-full h-11 rounded-xl border border-slate-200 bg-white px-3.5 text-sm text-slate-800 placeholder:text-slate-400 focus:outline-none focus:ring-2 focus:ring-[#0081B3]/40 focus:border-[#0081B3] transition"
        />
        {errors.name && (
          <p className="mt-1.5 text-xs text-red-500">{errors.name.message}</p>
        )}
      </div>

      {/* Email */}
      <div>
        <label className="block text-sm font-semibold text-slate-700 mb-1.5">
          Email Address <span className="text-red-500">*</span>
        </label>
        <input
          {...register("email")}
          type="email"
          placeholder="you@example.com"
          className="w-full h-11 rounded-xl border border-slate-200 bg-white px-3.5 text-sm text-slate-800 placeholder:text-slate-400 focus:outline-none focus:ring-2 focus:ring-[#0081B3]/40 focus:border-[#0081B3] transition"
        />
        {errors.email && (
          <p className="mt-1.5 text-xs text-red-500">{errors.email.message}</p>
        )}
      </div>

      {/* Topic */}
      <div>
        <label className="block text-sm font-semibold text-slate-700 mb-1.5">
          Topic <span className="text-red-500">*</span>
        </label>
        <select
          {...register("topic")}
          className="w-full h-11 rounded-xl border border-slate-200 bg-white px-3.5 text-sm text-slate-800 focus:outline-none focus:ring-2 focus:ring-[#0081B3]/40 focus:border-[#0081B3] transition appearance-none"
          defaultValue=""
        >
          <option value="" disabled>
            Select a topic…
          </option>
          {TOPICS.map((t) => (
            <option key={t} value={t}>
              {t}
            </option>
          ))}
        </select>
        {errors.topic && (
          <p className="mt-1.5 text-xs text-red-500">{errors.topic.message}</p>
        )}
      </div>

      {/* Message */}
      <div>
        <label className="block text-sm font-semibold text-slate-700 mb-1.5">
          Message <span className="text-red-500">*</span>
        </label>
        <textarea
          {...register("message")}
          rows={5}
          placeholder="Tell us what's going on…"
          className="w-full rounded-xl border border-slate-200 bg-white px-3.5 py-2.5 text-sm text-slate-800 placeholder:text-slate-400 focus:outline-none focus:ring-2 focus:ring-[#0081B3]/40 focus:border-[#0081B3] transition resize-none"
        />
        {errors.message && (
          <p className="mt-1.5 text-xs text-red-500">{errors.message.message}</p>
        )}
      </div>

      {/* Submit */}
      <button
        type="submit"
        disabled={isSubmitting}
        className="w-full h-11 rounded-xl bg-[#0081B3] hover:bg-[#0070A0] disabled:opacity-60 text-white font-bold text-sm transition-colors flex items-center justify-center gap-2"
      >
        {isSubmitting ? (
          <>
            <Loader2 className="w-4 h-4 animate-spin" />
            Sending…
          </>
        ) : (
          "Send Message"
        )}
      </button>

      <p className="text-center text-xs text-slate-400">
        Or email us directly at{" "}
        <a
          href="mailto:businessxteam@gmail.com"
          className="text-[#0081B3] hover:underline"
        >
          businessxteam@gmail.com
        </a>
      </p>
    </form>
  );
}
